#!/bin/bash


## Copy resources over

PWD=`pwd`;
RES="$PWD/res";
HOME_SRC="$RES/HOME";

HOME_TARGET="$HOME";

if [ $# -gt 0 ]; then
	HOME_TARGET=$1;
fi;

if [ ! -d $HOME_TARGET ]; then
	echo "🚨  Invalid home directory \"$HOME_TARGET\"";
	exit 1;
fi;

rsync -r "$HOME_SRC/" "$HOME_TARGET";


## Check for scripts you may want
declare -a scripts=("git" "php" "compass" "go");
for i in "${scripts[@]}"
do
	which "$i" &> /dev/null;
	val=$?;
	if [ $val -ne 0 ]; then
		echo -e "⚠️ You're missing \033[34m$i\033[0m, maybe you want that.";
	fi;
done

echo "🎈 DONE!";